server.port=8080

# URLs de los microservicios internos
ms-auth.url=http://localhost:8082
ms-usuario.url=http://localhost:8081
ms-academico.url=http://localhost:8083

# El mismo secret que usa ms-auth para firmar los JWT
jwt.secret=misecretatuysuperaguantadadesdeprotegidodelmundoentero

# Logs para ver el tráfico que pasa por el BFF
logging.level.cl.colegio.bff=DEBUG
